<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <AssemblyName>FamilyRelationsAdoption</AssemblyName>
    <Description>This RimWorld mod adds adoptive relationships to the game.</Description>
    <Version>1.2.0</Version>
    <Authors>Rycon</Authors>
    <OutputPath>../Assemblies</OutputPath>
    <LangVersion>latest</LangVersion>
    <DebugType>embedded</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Krafs.Rimworld.Ref" Version="1.6.*-*" />
    <PackageReference Include="Lib.Harmony" Version="2.4.2" />
  </ItemGroup>

</Project>
